### ISSUE TITLE
How can I apply this function to my GUI design? 

### ISSUE THREAD

**Issue by Liskelleo** [yjg30737/pyqt-search-bar-menu#1]
Hi, there. How do I set triggers corresponding to each action and connect them to slot functions?
Looking forward to your reply ^_^

**Comment by yjg30737** [comment]
```python
from PyQt5.QtWidgets import QMainWindow, QApplication
from pyqt_search_bar_menu import SearchBarMenu


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.__initUi()

    def __initUi(self):
        menubar = self.menuBar()
        filemenu = menubar.addMenu('File')

        searchBarMenu = SearchBarMenu('A Bunch of Actions', self)

        for i in range(5):
            searchBarMenu.addAction(f'Action{i+1}')

        filemenu.triggered.connect(self.__triggered)
        filemenu.addMenu(searchBarMenu)

        menubar.addMenu(filemenu)
        self.setMenuBar(menubar)

    def __triggered(self, action):
        text = action.text()
        print(text)


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    ex = MainWindow()
    ex.show()
    app.exec_()
```

Sorry for the belated reply.

If you have any questions, don't hesitate to ask.

**Comment by Liskelleo** [comment]
Thank you and best wishes to you^^

在 2022年12月19日，08:09，Jung Gyu Yoon ***@***.***> 写道：

﻿

from PyQt5.QtWidgets import QMainWindow, QApplication
from pyqt_search_bar_menu import SearchBarMenu


class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.__initUi()

    def __initUi(self):
        menubar = self.menuBar()
        filemenu = menubar.addMenu('File')

        searchBarMenu = SearchBarMenu('A Bunch of Actions', self)

        for i in range(5):
            searchBarMenu.addAction(f'Action{i+1}')

        filemenu.triggered.connect(self.__triggered)
        filemenu.addMenu(searchBarMenu)

        menubar.addMenu(filemenu)
        self.setMenuBar(menubar)

    def __triggered(self, action):
        text = action.text()
        print(text)


if __name__ == "__main__":
    import sys

    app = QApplication(sys.argv)
    ex = MainWindow()
    ex.show()
    app.exec_()

Sorry for the belated reply.

If you have any questions, don't hesitate to ask.

**Comment by Liskelleo** [comment]
Thank you and best wishes to you^^
